# 定时任务：每天更新 live 文件并提交
name: Schedule
on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次（UTC 0:00）
  workflow_dispatch: # 开启手动触发
env:
  USE_LOCAL_URLS: true
jobs:
  update-live-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Generate Live Files
        run: |
          pnpm start:prod

      - name: Upload Live Files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: live-files  # 下载时的文件名
          path: lives.txt lives.m3u          # 要上传的文件夹或文件路径

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update live files [skip ci]"
          file_pattern: '*.txt *.m3u'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
